from prompt import (
    DATA_GEN_SYSTEM_PROMPT,
    HOTPOTQA_TASK_NAME,
    HOTPOTQA_TASK_DESCRIPTION,
    SCIENCEQA_TASK_NAME,
    SCIENCEQA_TASK_DESCRIPTION,
    SCIENCEQA_DATA_GEN_HUMAN_PROMPT,
    HOTPOTQA_DATA_GEN_HUMAN_PROMPT
)
system_prompt = DATA_GEN_SYSTEM_PROMPT
print(system_prompt.format(task_name = HOTPOTQA_TASK_NAME, task_description = HOTPOTQA_TASK_DESCRIPTION))